* Introduction
This repo has a collection of information on different hydrological data sources, and information on how to obtain data from them.

I made this for personal purposes and am updating it as I learn more about the data sources, or when I find something new, so it is not an exhaustive list by any means. Feel free to suggests edits or additions through issues or pull requests.

* TOC :noexport:TOC:
- [[#introduction][Introduction]]
- [[#rainfall][Rainfall]]
  - [[#us-hourly-precipitation-data][U.S. Hourly Precipitation Data]]
- [[#streamflow][Streamflow]]
- [[#soil][Soil]]
- [[#geospatial-data][Geospatial data]]

* Rainfall

** U.S. Hourly Precipitation Data

Link: https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00313

#+begin_quote
Hourly Precipitation Data (HPD) is digital data set DSI-3240, archived at the National Climatic Data Center (NCDC). The primary source of data for this file is approximately 5,500 US National Weather Service (NWS), Federal Aviation Administration (FAA), and cooperative observer stations in the United States of America, Puerto Rico, the US Virgin Islands, and various Pacific Islands. The earliest data dates vary considerably by state and region: Maine, Pennsylvania, and Texas have data since 1900. The western Pacific region that includes Guam, American Samoa, Marshall Islands, Micronesia, and Palau have data since 1978. Other states and regions have earliest dates between those extremes. The latest data in all states and regions is from the present day.
#+end_quote

* Streamflow
[[https://waterdata.usgs.gov/nwis/][USGSWater Data for the Nation]] has many types of data related to water. For the streamflow data.

- Surface Water - Water flow and levels in streams and lakes.
- Groundwater - Water levels in wells.
- Water Quality - Chemical and physical data for streams, lakes, springs, wells and other sites.
- Water Use - Water use information.

There are buttons there for all of them, for example the daily data for streamflow can be found by clicking ~Surface Water~ then similar page with options will come up and then clicking ~Daily Data~.

There are a lot of choices on [[https://waterdata.usgs.gov/nwis/dv/?referred_module=sw][that page]] reached by the above step. To download data you can choose appropriate choices. If you chose some options and submit you'll get more options about the actual data, like which parameter you want to download and which format. You can also see the available data stations in a map. You can filter by many things, if you want suppose just ohio river stations instead of whole region, you can choose hydrologic region and station name for first, and later choose Ohio hydrologic region with partial match for ~ohio river~ in station name. 

* Soil

* Geospatial data
https://www.usgs.gov/educational-resources/usgs-geospatial-data-sources

* Climate projection Data
Link: https://esgf-node.llnl.gov/projects/cmip6/

#+begin_quote
The Coupled Model Intercomparison Project, which began in 1995 under the auspices of the World Climate Research Programme (WCRP), is now in its sixth phase (CMIP6). CMIP6 coordinates somewhat independent model intercomparison activities and their experiments which have adopted a common infrastructure for collecting, organizing, and distributing output from models performing common sets of experiments. The simulation data produced by models under previous phases of CMIP have been used in thousands of research papers (some of which are listed here), and the multi-model results provide some perspective on errors and uncertainty in model simulations. This information has proved invaluable in preparing high profile reports assessing our understanding of climate and climate change (e.g., the IPCC Assessment Reports).
#+end_quote

There are different portals based on the locations, the ones for USA is:
- USA, PCMDI/LLNL (California) - https://esgf-node.llnl.gov/search/cmip6/

The cmip6 data is explained in details in [[./cmip6.org]]
