* Introduction
This repo has a collection of information on different hydrological data sources, and information on how to obtain data from them.

I made this for personal purposes and am updating it as I learn more about the data sources, or when I find something new, so it is not an exhaustive list by any means. Feel free to suggests edits or additions through issues or pull requests.

* TOC :noexport:TOC:
- [[#introduction][Introduction]]
- [[#rainfall][Rainfall]]
  - [[#us-hourly-precipitation-data][U.S. Hourly Precipitation Data]]
- [[#streamflow][Streamflow]]
- [[#soil][Soil]]
- [[#geospatial-data][Geospatial data]]

* Rainfall

** U.S. Hourly Precipitation Data

Link: https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00313

#+begin_quote
Hourly Precipitation Data (HPD) is digital data set DSI-3240, archived at the National Climatic Data Center (NCDC). The primary source of data for this file is approximately 5,500 US National Weather Service (NWS), Federal Aviation Administration (FAA), and cooperative observer stations in the United States of America, Puerto Rico, the US Virgin Islands, and various Pacific Islands. The earliest data dates vary considerably by state and region: Maine, Pennsylvania, and Texas have data since 1900. The western Pacific region that includes Guam, American Samoa, Marshall Islands, Micronesia, and Palau have data since 1978. Other states and regions have earliest dates between those extremes. The latest data in all states and regions is from the present day.
#+end_quote

* Streamflow

* Soil

* Geospatial data
https://www.usgs.gov/educational-resources/usgs-geospatial-data-sources

* Climate projection Data
Link: https://esgf-node.llnl.gov/projects/cmip6/

#+begin_quote
The Coupled Model Intercomparison Project, which began in 1995 under the auspices of the World Climate Research Programme (WCRP), is now in its sixth phase (CMIP6). CMIP6 coordinates somewhat independent model intercomparison activities and their experiments which have adopted a common infrastructure for collecting, organizing, and distributing output from models performing common sets of experiments. The simulation data produced by models under previous phases of CMIP have been used in thousands of research papers (some of which are listed here), and the multi-model results provide some perspective on errors and uncertainty in model simulations. This information has proved invaluable in preparing high profile reports assessing our understanding of climate and climate change (e.g., the IPCC Assessment Reports).
#+end_quote

There are different portals based on the locations, the ones for USA is:
- USA, PCMDI/LLNL (California) - https://esgf-node.llnl.gov/search/cmip6/

The cmip6 data is explained in details in [[./cmip6.org]]
